# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-16 20:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        ('registrations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='participation',
            name='participant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='registrations.Participant'),
        ),
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='events.Category'),
        ),
    ]
