# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-17 08:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20170917_0217'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participation',
            old_name='confirmed',
            new_name='cr_approved',
        ),
        migrations.AddField(
            model_name='participation',
            name='pcr_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
