# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-15 08:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_participation'),
        ('registrations', '0002_captain_groupleader_participant'),
    ]

    operations = [
        migrations.AddField(
            model_name='participation',
            name='g_leader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registrations.GroupLeader'),
        ),
    ]
