# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-17 08:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20170917_1426'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participation',
            old_name='pcr_confirmed',
            new_name='pcr_approved',
        ),
    ]
