# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-26 17:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20170917_1429'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='description',
            new_name='rules',
        ),
        migrations.AddField(
            model_name='event',
            name='contact',
            field=models.CharField(default='', max_length=140),
        ),
    ]
