# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-04 21:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20170926_2244'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='detail_rules',
            field=models.TextField(blank=True, default='', max_length=1000, null=True),
        ),
    ]
