# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-06 04:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_event_detail_rules'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='detail_rules',
            field=models.TextField(blank=True, default='', max_length=3000, null=True),
        ),
    ]
