# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-16 11:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_auto_20171016_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='attendance',
            name='passed_count',
            field=models.IntegerField(default=0),
        ),
    ]
