# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-25 15:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ems', '0019_auto_20171021_1451'),
        ('events', '0009_auto_20171016_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='bitsian',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ems.Bitsian'),
        ),
    ]
