# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-14 18:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.BigIntegerField()),
                ('password', models.CharField(max_length=100)),
                ('day', models.IntegerField(default=0)),
                ('score', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(default='', max_length=60)),
                ('question_no', models.IntegerField(default=0)),
                ('day', models.IntegerField(default=0)),
                ('answer', models.CharField(max_length=100)),
                ('points', models.IntegerField(default=0)),
            ],
        ),
    ]
