# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-15 09:45
from __future__ import unicode_literals

from django.db import migrations, models
import wordwars.models


class Migration(migrations.Migration):

    dependencies = [
        ('wordwars', '0002_auto_20171015_0239'),
    ]

    operations = [
        migrations.AddField(
            model_name='day',
            name='announced',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='image',
            field=models.ImageField(null=True, upload_to=wordwars.models.question_image_path),
        ),
    ]
