# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-26 05:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordwars', '0003_auto_20171015_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
