# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-25 08:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20171025_1347'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartBill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('time_paid', models.DateTimeField(auto_now=True)),
                ('two_thousands', models.IntegerField(blank=True, default=0, null=True)),
                ('five_hundreds', models.IntegerField(blank=True, default=0, null=True)),
                ('two_hundreds', models.IntegerField(blank=True, default=0, null=True)),
                ('hundreds', models.IntegerField(blank=True, default=0, null=True)),
                ('fifties', models.IntegerField(blank=True, default=0, null=True)),
                ('twenties', models.IntegerField(blank=True, default=0, null=True)),
                ('tens', models.IntegerField(blank=True, default=0, null=True)),
                ('draft_number', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('draft_amount', models.IntegerField(blank=True, default=0, null=True)),
                ('two_thousands_returned', models.IntegerField(blank=True, default=0, null=True)),
                ('five_hundreds_returned', models.IntegerField(blank=True, default=0, null=True)),
                ('two_hundreds_returned', models.IntegerField(blank=True, default=0, null=True)),
                ('hundreds_returned', models.IntegerField(blank=True, default=0, null=True)),
                ('fifties_returned', models.IntegerField(blank=True, default=0, null=True)),
                ('twenties_returned', models.IntegerField(blank=True, default=0, null=True)),
                ('tens_returned', models.IntegerField(blank=True, default=0, null=True)),
                ('cart', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='store.Cart')),
            ],
        ),
    ]
