# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-25 21:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_item_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='cart',
        ),
        migrations.AddField(
            model_name='item',
            name='cart',
            field=models.ManyToManyField(through='store.Sale', to='store.Cart')
        ),
    ]
