# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-25 22:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_auto_20171026_0323'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='quantity_left',
            field=models.IntegerField(default=0),
        ),
    ]
