# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-25 22:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_item_quantity_left'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='colour',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.Colour'),
        ),
        migrations.AddField(
            model_name='sale',
            name='size',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.Size'),
        ),
    ]
