# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-25 23:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_auto_20171026_0400'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='cart_token',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
