# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-26 10:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ems', '0019_auto_20171021_1451'),
        ('store', '0011_cart_cart_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='bitsian',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ems.Bitsian'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='participant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='registrations.Participant'),
        ),
    ]
