# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-27 13:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_auto_20171027_1826'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mainitem',
            old_name='quantity',
            new_name='quantity_left',
        ),
    ]
