# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-28 06:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_auto_20171027_1926'),
    ]

    operations = [
        migrations.CreateModel(
            name='Combo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(default=0)),
                ('items', models.ManyToManyField(to='store.Item')),
            ],
        ),
    ]
