# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-28 06:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_combo'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainCombo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('combo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Combo')),
                ('mainitems', models.ManyToManyField(to='store.MainItem')),
            ],
        ),
        migrations.AddField(
            model_name='cart',
            name='combos',
            field=models.ManyToManyField(to='store.MainCombo'),
        ),
    ]
