# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-28 06:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_auto_20171028_1207'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='combos',
            new_name='maincombos',
        ),
    ]
