# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-15 08:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registrations', '0002_captain_groupleader_participant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bhavan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('time_paid', models.DateTimeField(auto_now=True)),
                ('two_thousands', models.IntegerField(blank=True, default=0, null=True)),
                ('five_hundreds', models.IntegerField(blank=True, default=0, null=True)),
                ('hundreds', models.IntegerField(blank=True, default=0, null=True)),
                ('fifties', models.IntegerField(blank=True, default=0, null=True)),
                ('twenties', models.IntegerField(blank=True, default=0, null=True)),
                ('tens', models.IntegerField(blank=True, default=0, null=True)),
                ('draft_number', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('draft_amount', models.IntegerField(blank=True, default=0, null=True)),
                ('two_thousands_returned', models.IntegerField(blank=True, default=0, null=True)),
                ('five_hundreds_returned', models.IntegerField(blank=True, default=0, null=True)),
                ('hundreds_returned', models.IntegerField(blank=True, default=0, null=True)),
                ('fifties_returned', models.IntegerField(blank=True, default=0, null=True)),
                ('twenties_returned', models.IntegerField(blank=True, default=0, null=True)),
                ('tens_returned', models.IntegerField(blank=True, default=0, null=True)),
                ('coaches_list', models.CharField(blank=True, max_length=200, null=True)),
                ('g_leader', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='registrations.GroupLeader')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.CharField(max_length=30)),
                ('vacancy', models.IntegerField()),
                ('bhavan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='regsoft.Bhavan')),
            ],
        ),
    ]
