# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-23 11:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regsoft', '0003_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='time',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
