# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-23 14:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regsoft', '0004_note_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='two_hundreds',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='two_hundreds_returned',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
