# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-29 19:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regsoft', '0005_auto_20171023_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='vacancy',
            field=models.IntegerField(default=0),
        ),
    ]
