# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-24 20:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messportal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profshowbill',
            name='buyer_id',
            field=models.CharField(max_length=20),
        ),
    ]
