# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-25 14:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messportal', '0002_auto_20171025_0141'),
    ]

    operations = [
        migrations.AddField(
            model_name='profshowbill',
            name='bits_id',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
