# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-25 15:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_attendance_bitsian'),
        ('messportal', '0003_profshowbill_bits_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='BitsProfShowBill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now=True)),
                ('buyer_id', models.CharField(max_length=20)),
                ('quantity', models.IntegerField(default=0)),
                ('created_by', models.CharField(max_length=50)),
                ('amount', models.IntegerField(default=0)),
                ('prof_show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.ProfShow')),
            ],
        ),
    ]
