# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-28 13:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ems', '0023_auto_20171028_0756'),
        ('registrations', '0022_auto_20171024_2329'),
        ('messportal', '0004_bitsprofshowbill'),
    ]

    operations = [
        migrations.AddField(
            model_name='bitsprofshowbill',
            name='bitsian',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ems.Bitsian'),
        ),
        migrations.AddField(
            model_name='profshowbill',
            name='participant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='registrations.Participant'),
        ),
    ]
