# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-02 09:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmain',
            name='orderno',
            field=models.IntegerField(default=0),
        ),
    ]
