# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-16 20:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import registrations.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('regsoft', '0001_initial'),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.IntegerField(default=0)),
                ('amount_deduct', models.IntegerField(default=0)),
                ('created_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='IntroReg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('city', models.CharField(max_length=20)),
                ('phone_no', models.BigIntegerField()),
                ('email_id', models.EmailField(max_length=254, unique=True)),
                ('literary', models.BooleanField(default=False)),
                ('dance', models.BooleanField(default=False)),
                ('music', models.BooleanField(default=False)),
                ('theater', models.BooleanField(default=False)),
                ('fashion_parade', models.BooleanField(default=False)),
                ('find_out_about_oasis', models.CharField(max_length=100)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registrations.College')),
                ('events', models.ManyToManyField(blank=True, to='events.Event')),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('barcode', models.CharField(max_length=50, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('city', models.CharField(max_length=100, null=True)),
                ('state', models.CharField(max_length=50)),
                ('phone', models.BigIntegerField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=10)),
                ('profile_pic', models.ImageField(upload_to=registrations.models.user_directory_path)),
                ('email_verified', models.BooleanField(default=False)),
                ('email_token', models.CharField(blank=True, max_length=32, null=True)),
                ('cr_approved', models.BooleanField(default=False)),
                ('is_cr', models.BooleanField(default=False)),
                ('pcr_approved', models.BooleanField(default=False)),
                ('firewallz_passed', models.BooleanField(default=False)),
                ('controlz', models.BooleanField(default=False, verbose_name='controlz passed')),
                ('recnacc_time', models.DateTimeField(null=True)),
                ('is_g_leader', models.BooleanField(default=False)),
                ('bill', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='regsoft.Bill')),
                ('events', models.ManyToManyField(through='events.Participation', to='events.Event')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registrations.Group')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='regsoft.Room')),
            ],
        ),
    ]
