# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-05 21:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('is_displayed', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='IntroReg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('city', models.CharField(max_length=20)),
                ('phone_no', models.BigIntegerField()),
                ('email_id', models.EmailField(max_length=254, unique=True)),
                ('literary', models.BooleanField(default=False)),
                ('dance', models.BooleanField(default=False)),
                ('music', models.BooleanField(default=False)),
                ('theater', models.BooleanField(default=False)),
                ('fashion_parade', models.BooleanField(default=False)),
                ('find_out_about_oasis', models.CharField(max_length=100)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registrations.College')),
                ('events', models.ManyToManyField(blank=True, to='events.Event')),
            ],
        ),
    ]
