# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-15 08:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Captain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.BigIntegerField(default=0)),
                ('coach', models.CharField(max_length=200)),
                ('paid', models.BooleanField(default=False)),
                ('is_single', models.NullBooleanField()),
                ('total_players', models.IntegerField(default=1)),
                ('gender', models.CharField(choices=[('M', 'MALE'), ('F', 'FEMALE')], max_length=10)),
                ('barcode', models.CharField(max_length=50, null=True)),
                ('pcr_final', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Team Captains',
            },
        ),
        migrations.CreateModel(
            name='GroupLeader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=50)),
                ('phone', models.BigIntegerField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('gender', models.CharField(choices=[('M', 'MALE'), ('F', 'FEMALE')], max_length=10)),
                ('email_verified', models.BooleanField(default=False)),
                ('email_token', models.CharField(blank=True, max_length=32, null=True)),
                ('pcr_approved', models.BooleanField(default=False)),
                ('barcode', models.CharField(max_length=50, null=True)),
            ],
            options={
                'verbose_name_plural': 'Group Leaders',
            },
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('is_captain', models.BooleanField(default=False)),
                ('email', models.EmailField(max_length=254)),
                ('firewallz_passed', models.BooleanField(default=False)),
                ('controlz', models.BooleanField(default=False, verbose_name='controlz passed')),
                ('barcode', models.CharField(max_length=50, null=True)),
                ('recnacc_time', models.DateTimeField(null=True)),
            ],
        ),
    ]
