# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-17 00:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0002_participant_college'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='participant',
            name='pcr_final',
            field=models.BooleanField(default=False),
        ),
    ]
