# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-15 08:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_participation_g_leader'),
        ('regsoft', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('registrations', '0002_captain_groupleader_participant'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='bill',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='regsoft.Bill'),
        ),
        migrations.AddField(
            model_name='participant',
            name='captain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registrations.Captain'),
        ),
        migrations.AddField(
            model_name='participant',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='regsoft.Room'),
        ),
        migrations.AddField(
            model_name='groupleader',
            name='college',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registrations.College'),
        ),
        migrations.AddField(
            model_name='groupleader',
            name='events',
            field=models.ManyToManyField(blank=True, null=True, through='events.Participation', to='events.Event'),
        ),
        migrations.AddField(
            model_name='groupleader',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='captain',
            name='event',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='events.Event'),
        ),
        migrations.AddField(
            model_name='captain',
            name='g_leader',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='registrations.GroupLeader'),
        ),
    ]
