# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-17 08:30
from __future__ import unicode_literals

from django.db import migrations, models
import registrations.models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0003_auto_20170917_0604'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='head_of_society',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='participant',
            name='verify_docs',
            field=models.FileField(default=None, null=True, upload_to=registrations.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='participant',
            name='profile_pic',
            field=models.ImageField(null=True, upload_to=registrations.models.user_directory_path),
        ),
    ]
