# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-15 08:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0003_auto_20170915_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupleader',
            name='events',
            field=models.ManyToManyField(through='events.Participation', to='events.Event'),
        ),
    ]
