# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-17 08:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0004_auto_20170917_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='year_of_study',
            field=models.CharField(max_length=3, null=True),
        ),
    ]
