# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-17 08:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0005_participant_year_of_study'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='cr_approved',
        ),
    ]
