# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-17 17:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0007_auto_20170917_2258'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='amount_paid',
        ),
    ]
