# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-18 22:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0008_remove_group_amount_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='bill',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='regsoft.Bill'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='registrations.Group'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='payment_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='registrations.PaymentGroup'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
