# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-26 08:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0010_auto_20170919_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='controlz_paid',
            field=models.BooleanField(default=False),
        ),
    ]
