# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-27 00:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0011_participant_controlz_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='amount_paid',
            field=models.IntegerField(default=0),
        ),
    ]
