# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-27 01:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0012_participant_amount_paid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='amount_paid',
        ),
    ]
