# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-28 19:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0013_remove_participant_amount_paid'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='participant',
            name='email_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='registrations.EmailGroup'),
        ),
    ]
