# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-03 08:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0014_auto_20170929_0102'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='cr_approved',
            field=models.BooleanField(default=False),
        ),
    ]
