# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-13 13:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0015_participant_cr_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='group_code',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
