# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-13 14:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0016_group_group_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='curr_controlz_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='participant',
            name='curr_paid',
            field=models.BooleanField(default=False),
        ),
    ]
