# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-13 16:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0017_auto_20171013_2012'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='acco',
            field=models.BooleanField(default=False),
        ),
    ]
