# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-16 09:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0018_participant_acco'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckoutGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_retained', models.IntegerField(default=0)),
                ('created_time', models.DateTimeField(auto_now=True)),
                ('group_code', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='group',
            name='group_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='checkout_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='registrations.CheckoutGroup'),
        ),
    ]
