# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-17 17:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0019_auto_20171016_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='ems_code',
            field=models.CharField(default='', max_length=10, null=True),
        ),
    ]
