# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-24 17:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0021_auto_20171023_2004'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='bits_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='is_guest',
            field=models.BooleanField(default=False),
        ),
    ]
