# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-30 22:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0023_auto_20171031_0338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='group_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
