# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-01 14:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('registrations', '0025_auto_20171102_1537'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bitsian',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('long_id', models.CharField(blank=True, max_length=20, null=True)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('gender', models.CharField(blank=True, max_length=1, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('barcode', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('phone', models.BigIntegerField(default=0, null=True)),
                ('bhawan', models.CharField(blank=True, max_length=20, null=True)),
                ('room_no', models.IntegerField(default=0)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
