# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-16 18:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PitchPerfect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('g_leader', models.CharField(max_length=100)),
                ('members', models.CharField(max_length=600)),
                ('city', models.CharField(max_length=100)),
                ('college', models.CharField(max_length=100)),
                ('phone', models.CharField(default='', max_length=13)),
                ('email_address', models.EmailField(max_length=254, unique=True)),
                ('paid', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Pitch Perfect',
            },
        ),
        migrations.CreateModel(
            name='RapWars',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('phone', models.CharField(default='', max_length=13)),
                ('gender', models.CharField(max_length=6)),
                ('email_address', models.EmailField(max_length=254, unique=True)),
                ('paid', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Rap Wars',
            },
        ),
        migrations.CreateModel(
            name='Rocktaves',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('phone', models.CharField(default='', max_length=13)),
                ('gender', models.CharField(max_length=6)),
                ('email_address', models.EmailField(max_length=254, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Rocktaves',
            },
        ),
        migrations.CreateModel(
            name='StandUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('phone', models.CharField(default='', max_length=13)),
                ('gender', models.CharField(max_length=6)),
                ('email_address', models.EmailField(max_length=254, unique=True)),
            ],
            options={
                'verbose_name_plural': 'StandUp SandBox',
            },
        ),
        migrations.CreateModel(
            name='StreetDance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('g_leader', models.CharField(max_length=100)),
                ('members', models.CharField(max_length=600)),
                ('city', models.CharField(max_length=100)),
                ('college', models.CharField(max_length=100)),
                ('phone', models.CharField(default='', max_length=13)),
                ('email_address', models.EmailField(max_length=254, unique=True)),
                ('paid', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Street Dance',
            },
        ),
    ]
