# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-18 04:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preregistrations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pitchperfect',
            name='number_of_members',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='streetdance',
            name='number_of_members',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
