# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-12 13:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('preregistrations', '0003_rapwars'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pitchperfect',
            options={'verbose_name_plural': 'Pitch Perfect'},
        ),
        migrations.AlterModelOptions(
            name='rapwars',
            options={'verbose_name_plural': 'Rap Wars'},
        ),
        migrations.AlterModelOptions(
            name='rocktaves',
            options={'verbose_name_plural': 'Rocktaves'},
        ),
        migrations.AlterModelOptions(
            name='standup',
            options={'verbose_name_plural': 'StandUp SandBox'},
        ),
        migrations.AlterModelOptions(
            name='streetdance',
            options={'verbose_name_plural': 'Street Dance'},
        ),
    ]
