# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-15 15:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preregistrations', '0004_auto_20170612_1904'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='standup',
            name='paid',
        ),
        migrations.AddField(
            model_name='rapwars',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
