# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-22 23:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registrations', '0010_auto_20170919_1744'),
        ('events', '0004_auto_20170917_1429'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('rank', models.PositiveSmallIntegerField(default=0)),
                ('is_winner', models.BooleanField(default=False)),
                ('is_finalist', models.BooleanField(default=False)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Event')),
                ('leader', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='team_leader', to='registrations.Participant')),
                ('members', models.ManyToManyField(to='registrations.Participant')),
            ],
        ),
    ]
