# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-24 13:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ems', '0003_parameter'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='position',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
