# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-24 14:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ems', '0004_level_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bitsian',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('long_id', models.CharField(blank=True, max_length=20, null=True)),
                ('short_id', models.CharField(blank=True, max_length=10, null=True)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True)),
                ('college', models.CharField(blank=True, default='BITS Pilani', max_length=200, null=True)),
            ],
        ),
    ]
