# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-24 15:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ems', '0005_bitsian'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='label',
            name='var10max',
        ),
        migrations.RemoveField(
            model_name='label',
            name='var10name',
        ),
        migrations.RemoveField(
            model_name='label',
            name='var1max',
        ),
        migrations.RemoveField(
            model_name='label',
            name='var1name',
        ),
        migrations.RemoveField(
            model_name='label',
            name='var2max',
        ),
        migrations.RemoveField(
            model_name='label',
            name='var2name',
        ),
        migrations.RemoveField(
            model_name='label',
            name='var3max',
        ),
        migrations.RemoveField(
            model_name='label',
            name='var3name',
        ),
        migrations.RemoveField(
            model_name='label',
            name='var4max',
        ),
        migrations.RemoveField(
            model_name='label',
            name='var4name',
        ),
        migrations.RemoveField(
            model_name='label',
            name='var5max',
        ),
        migrations.RemoveField(
            model_name='label',
            name='var5name',
        ),
        migrations.RemoveField(
            model_name='label',
            name='var6max',
        ),
        migrations.RemoveField(
            model_name='label',
            name='var6name',
        ),
        migrations.RemoveField(
            model_name='label',
            name='var7max',
        ),
        migrations.RemoveField(
            model_name='label',
            name='var7name',
        ),
        migrations.RemoveField(
            model_name='label',
            name='var8max',
        ),
        migrations.RemoveField(
            model_name='label',
            name='var8name',
        ),
        migrations.RemoveField(
            model_name='label',
            name='var9max',
        ),
        migrations.RemoveField(
            model_name='label',
            name='var9name',
        ),
        migrations.RemoveField(
            model_name='parameter',
            name='level',
        ),
        migrations.AddField(
            model_name='parameter',
            name='label',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ems.Label'),
        ),
    ]
