# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-27 11:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ems', '0009_auto_20170927_0409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubdepartment',
            name='events',
            field=models.ManyToManyField(blank=True, to='events.Event'),
        ),
    ]
