# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-30 13:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ems', '0010_auto_20170927_1654'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='is_bitsian',
        ),
    ]
