# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-17 17:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ems', '0011_remove_team_is_bitsian'),
    ]

    operations = [
        migrations.AddField(
            model_name='bitsian',
            name='ems_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
