# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-19 13:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ems', '0012_bitsian_ems_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='bitsian',
            name='gender',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='judge',
            name='password',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
