# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-19 13:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ems', '0013_auto_20171019_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='judge',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
