# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-19 15:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ems', '0014_auto_20171019_1913'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubdepartment',
            name='password',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
