# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-20 10:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ems', '0016_auto_20171019_2139'),
    ]

    operations = [
        migrations.AddField(
            model_name='bitsian',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
