# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-26 21:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_attendance_bitsian'),
        ('ems', '0019_auto_20171021_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='bitsian',
            name='barcode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='clubdepartment',
            name='profshows',
            field=models.ManyToManyField(null=True, to='events.ProfShow'),
        ),
    ]
