# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-26 21:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ems', '0020_auto_20171027_0242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='judge',
            name='event',
        ),
        migrations.AddField(
            model_name='judge',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ems.Level'),
        ),
    ]
