# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-27 12:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ems', '0021_auto_20171027_0302'),
    ]

    operations = [
        migrations.RenameField(
            model_name='score',
            old_name='score',
            new_name='score_card',
        ),
        migrations.RemoveField(
            model_name='clubdepartment',
            name='password',
        ),
        migrations.RemoveField(
            model_name='judge',
            name='password',
        ),
        migrations.RemoveField(
            model_name='score',
            name='is_frozen',
        ),
        migrations.AddField(
            model_name='judge',
            name='frozen',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='judge',
            name='left_the_event',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='score',
            name='comments',
            field=models.TextField(default='{}'),
        ),
        migrations.AlterField(
            model_name='clubdepartment',
            name='profshows',
            field=models.ManyToManyField(to='events.ProfShow'),
        ),
    ]
