# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-28 02:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ems', '0022_auto_20171027_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='bitsian',
            name='bhawan',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='bitsian',
            name='room_no',
            field=models.IntegerField(default=0),
        ),
    ]
